import os
from pathlib import Path
BASE_DIR = Path('slot_extraction')
config = {
 'data_dir':'data',
 'embedding_dir':os.path.join('data','embedding_data'),
 'embedding_file_name':"sgns.financial.bigram-char",
 'input_embedding_file':"input_char_embedding.npy",
 'input_word_embedding_file':"input_word_embedding.npy",
 'vocab_file':"vocab.txt",
 'slot_list_root_path':os.path.join('data','slot_pattern'),
 'slot_file_name':"base_slot_list",
 'log_dir': os.path.join('output','log'),
 'data_file_name':'orig_data_train.txt',
 'train_valid_data_dir':'train_valid_data',
 'train_data_text_name':'train_split_data_text.npy',
 'valid_data_text_name':'valid_split_data_text.npy',
 'train_data_tag_name':'train_split_data_tag.npy',
 'valid_data_tag_name':'valid_split_data_tag.npy',
 'test_data_text_name':'test_data_text.npy',
 'test_data_tag_name':'test_data_tag.npy',
 'train_data_text_word_name':'train_word_split_data.npy',
 'valid_data_text_word_name':'valid_word_split_data.npy',
 'test_data_text_word_name':'test_word_split_data.npy',
 'model_dir':os.path.join('output','model','checkpoint'),
 'base_model_dir':os.path.join('output','model','base_model','checkpoint'),
 'orig_dev':'orig_data_dev.txt',
 'orig_test':'orig_data_test.txt',
 "pb_model_dir":os.path.join('output','model','saved_model'),
 "base_pb_model_dir":os.path.join('output','model','base_model','saved_model'),
 "standard_slot_description":os.path.join('data','slot_pattern','slot_description.csv'),
 "cnn_model_dir":os.path.join('output','model','cnn_model','checkpoint'),
 "cnn_pb_model_dir":os.path.join('output','model','cnn_model','saved_model'),
 "lstm_only_dlloss_model_dir":os.path.join('output','model','lstm_only_dlloss_model','checkpoint'),
 "lstm_only_dlloss_pb_model_dir":os.path.join('output','model','lstm_only_dlloss_model','saved_model'),
 "lstmcrf_lesslabel_model_dir":os.path.join('output','model','lstm_only_dlloss_model','checkpoint'),
 "lstmcrf_lesslabel_pb_model_dir":os.path.join('output','model','lstm_only_dlloss_model','saved_model'),
 "lstmcrf_completelabel_model_dir":os.path.join('output','model','lstmcrf_completelabel_model','checkpoint'),
 "lstmcrf_completelabel_pb_model_dir":os.path.join('output','model','lstmcrf_completelabel_model','saved_model'),
 "lstmcrf_completelabel_wordemb_model_dir":os.path.join('output','model','lstmcrf_completelabel_wordemb_model','checkpoint'),
 "lstmcrf_completelabel_wordemb_pb_model_dir":os.path.join('output','model','lstmcrf_completelabel_wordemb_model','saved_model'),
 "lstmcrf_cnn_completelabel_wordemb_model_dir":os.path.join('output','model','lstmcrf_cnn_completelabel_wordemb_model','checkpoint'),
 "lstmcrf_cnn_completelabel_wordemb_pb_model_dir":os.path.join('output','model','lstmcrf_cnn_completelabel_wordemb_model','saved_model'),

}
# print(os.path.join(config.get("train_valid_data_dir"),config.get("train_data_text_name")))
# print(os.path.join(config.get("train_valid_data_dir"),config.get("train_data_text_name")))